interledgerjs/ilp-core

README.md, src/lib/client.js, src/lib/payment.js, test/clientSpec.js, test/paymentSpec.js
This provides a way for users to extend the functionality of the ilp core client. Extensions can
hook into client events and access client methods. Extension methods can be accessed via
client[name], where `name` is the string returned by `Extension.getName()`
Also, `client.createPayment` will throw an error if no `executionCondition` is given, unless `unsafeOptimisticTransport` is set to `true`.
=> ILP client extensions & explicit Optimistic payments

package.json, src/lib/client.js, test/clientSpec.js
Get quotes from multiple connectors and use the best one.
Closes https://github.com/interledger/js-ilp-core/issues/13
=> multiple connectors

README.md
addresses https://github.com/interledger/js-ilp-core/issues/19#issuecomment-232364939
fixes https://github.com/interledger/js-ilp-core/issues/18
=> Make example use 10 sec timeout, no es6 import, include waitForConnection

src/lib/client.js, test/clientSpec.js
In some cases I might want to specify a list of connectors to get quotes from. I also need this working with the [plugin-virtual](https://github.com/interledger/js-ilp-plugin-virtual). [See this](https://github.com/interledger/js-ilp-plugin-virtual/blob/master/src/plugin/noob_plugin.js#L221-L225).
=> Take connectors as a param on quote

README.md, package.json, src/lib/client.js, src/lib/core.js, src/lib/util.js, test/coreSpec.js, test/mocks/mock-client.js, test/mocks/mock-plugin.js
If the core doesn't have a plugin for the destination ledger, `Core#quote` will ask a connector closer to the destination.
Depends on https://github.com/interledger/five-bells-routing/pull/8
=> feat: [BREAKING] Core#quote

src/lib/client.js, src/lib/core.js, test/mocks/mock-client.js, test/mocks/mock-plugin.js
https://github.com/interledger/js-ilp-plugin-bells/issues/26
=> fix: getAccount returns a Promise

README.md, src/lib/client.js, test/clientSpec.js
oops -- another breaking change. let's wait to bump the version with this one until we have another set of breaking features to add. this removes something that isn't being used right now so it can stay in until the next major release
resolves https://github.com/interledger/js-ilp-core/issues/33
=> remove extensions

package.json, src/lib/core.js, src/lib/util.js, test/coreSpec.js
Fixes https://github.com/interledger/js-ilp-core/issues/42
=> fix: support subledger quotes

circle.yml, package.json
resolves https://github.com/interledger/js-ilp-core/issues/34
=> Run integration tests

src/lib/client.js, test/clientSpec.js, test/mocks/mock-plugin.js
=> fix: support same-ledger payments

src/lib/client.js, test/clientSpec.js, test/mocks/mock-client.js, test/mocks/mock-plugin.js
Depends on https://github.com/interledger/js-ilp-plugin-bells/pull/40
Fixes #43, #48
=> feat: clientOpts.connectors; getConnectors

src/lib/client.js, test/clientSpec.js
=> fix: sendQuotedPayment should set transfer.ledger

README.md
adds badges for NPM, Circle CI, and Codecov
=> Docs: add badges

README.md
Add some more specification of that field to the README, for the quote and constructor methods.
=> docs: document "connectors" in README.md

src/lib/client.js
If the `pluginOpts` parameter is an EventEmitter (it has the `.on` function, which will never happen if `pluginOpts` is a JSON-able object), then it will be used as the plugin instance for a client.
=> Feat: allow a fully instantiated plugin in place of pluginOpts

src/lib/client.js, test/clientSpec.js
Fixes https://github.com/interledgerjs/ilp-core/issues/70
=> fix: use one listener for all incoming messages

src/lib/client.js, src/lib/core.js, test/clientSpec.js, test/coreSpec.js
Related to https://github.com/interledger/rfcs/pull/128 and https://github.com/interledgerjs/ilp-plugin-bells/pull/74.
=> feat: relay connect() options

src/lib/client.js, test/clientSpec.js
Not needed anymore, just call `connect()`.
=> feat: [BREAKING] remove waitForConnection()

package.json, src/lib/core.js, test/coreSpec.js
Related to https://github.com/interledgerjs/ilp-connector/issues/270 and https://github.com/interledgerjs/ilp-connector/issues/269
Depends on https://github.com/interledgerjs/ilp-routing/pull/21
=> feat: add destination{Precision,Scale} to quote

src/lib/client.js, src/lib/core.js, test/clientSpec.js, test/coreSpec.js, test/mocks/mock-client.js, test/mocks/mock-plugin.js
Also use sync get{Account,Info}
Related to https://github.com/interledger/rfcs/pull/143
Requires https://github.com/interledgerjs/ilp-plugin-bells/pull/87
=> feat: BREAKING: make getConnectors return IlpAddress[]

package.json
=> fix: ilp-routing requirement in line with improved-route-broadcast 

src/lib/client.js
=> refactor: add more debug output for quoting and messages

package.json, src/lib/client.js, src/lib/core.js, test/clientSpec.js, test/coreSpec.js
Depends on https://github.com/interledgerjs/ilp-routing/pull/32
=> BREAKING new ilp-packet format

.npmignore, CHANGELOG.md, package.json, src/lib/client.js, test/clientSpec.js
=> Use new field names for sendMessage

circle.yml
See https://circleci.com/gh/interledgerjs/ilp-core
=> chore: use node 7
